include:
  - project: 'deploy-app/fe-scripts'
    ref: master
    file: '/jobs/private-angular.gitlab-ci.yml'

publish-and-deploy-test:
    services:
        - docker:stable-dind
    cache: {}
    stage: deploy
    interruptible: true
    except:
        - schedules
    script:
        - apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
        - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        - apt-get update && apt-get install -y docker-ce-cli
        - ./ci-scripts/prepare-ci.sh install-app --remote "$APP_GIT" --angular
        - git clone git@gitlab.protontech.ch:proton/devops/test-infra.git --depth 1
        - ./test-infra/kube-install-bins.sh
        - ./test-infra/docker-login-gcr.sh
        - EXTRA_REGISTRY_IMAGE=gcr.io/proton-dev-ops/webapp ./tasks/build-image.sh
        - export DIST_IMAGE="gcr.io/proton-dev-ops/webapp/dist:commit-${CI_COMMIT_SHORT_SHA}"
        - ./test-infra/kube-deploy.sh -a=mail-fe -i="${DIST_IMAGE}" -b="${CI_COMMIT_REF_NAME}" --update-gitlab-status
    dependencies: []
